const IMAGES = {
    ForgotPass: require('./forgotpass.png'),
    GiatGiay: require('./giatgiay.png'),
    GiatHap: require('./giathap.png'),
    GiatSay: require('./giatsay.png'),
    GiatTui: require('./giatui.png'),
    ImgShop: require('./imgshop.png'),
    ImgShop1: require('./imgshop2.png'),
    ImgShop2: require('./imgshop3.png'),
    DanhMuc: require('./list.png'),
    Login: require('./login.png'),
    Logo: require('./logo.png'),
    NhuomVai: require('./nhuomvai.png'),
    OnBoarding: require('./onboard_bg1.png'),
    OnBoarding1: require('./onboard_bg2.png'),
    OnBoarding2: require('./onboard_bg3.png'),
    OTP: require('./otp.png'),
    SignUp: require('./signup.png'),
    SlideShow: require('./slideshow1.png'),
    SlideShow1: require('./slideshow2.png'),
    SlideShow2: require('./slideshow3.png'),
    demoImage:require('./bo_vest.png'),
    iconStatus: require('./iconstatus.png'),
    iconadress: require('./iconadress.png'),
    iconpayment: require('./iconpayment.png'),
    line: require('./line.png'),
    star: require("./star.png"),
    check: require("./check.png"),
    iconshop: require("./iconshop.png"),
    camera_alt: require("./camera_alt.png"),
    photo_camera: require("./photo_camera.png"),
    star1: require("./star1.png"),
    star2: require("./star2.png"),
    BackGroundShop:require('./shopdetail.png'),
    loading_image: require("./loading_image.jpg"),
    SuccessPayment:require('./success_payment.png'),
    AnhBia: require('./anhbia.jpg'),
    user: require('./user.png')
    
}
export default IMAGES
