const COLORS = {
    HEX_BLACK : '#0C0F14',
    HEX_LIGHT_GRAY : '#52555A',
    HEX_LIGHT_GREY: '#AEAEAE',
    WHITE : '#FFFFFF',
    RED : 'red',
    OCEAN_BLUE: '#007CAB',
    AZURE_BLUE: '#00ADEF',
    LIGHT_SKY_BLUE: '#95C9DD',
    BLUE_GRAY: '#60778C',
    WHISPER_GRAY:'#F0F0F0',
    PRIMARY: '#25565F',
    DARK_BLUE: '#0D0140'
}

export default COLORS;